_name_: qautoaudio
path: musdb18stereo
bits: 16
sample_len: 12288 # 131072
train_percentage: 0.88
quantization: linear
drop_last: true
context_len: null
pad_len: null
is_stereo: true
interleaving_strategy: temporal  # Options: temporal, blocking
__l_max: ${eval:${.sample_len} * 2}  # Automatically double the sample_len for stereo
